const FakeClients = {
	Data: [
		{
			ID: 52,
			OwnerPersonalNo: null,
			OwnerPIB: null,
			OwnerName: 'Borko',
			OwnerSurnameOrBusinessName: 'Drazilovic',
			OwnerAddress: null,
			OwnerPhone: null,
			OwnerEmail: null,
			UserPersonalNo: null,
			UserPIB: null,
			UserName: null,
			UserSurnameOrBusinessName: null,
			UserAddress: null,
			UserPhone: null,
			UserEmail: null,
			RecommendedBy: 'Kum Peca',
			Vehicles: [
				{
					ID: 51,
					RegistrationNumber: 'BG',
					FirstRegistrationDate: null,
					ProductionYear: null,
					Make: 'Fiat',
					Model: 'Croma',
					Type: null,
					EnginePowerKW: null,
					EngineCapacity: null,
					FuelType: null,
					PowerWeightRatio: null,
					Mass: null,
					MaxPermissibleLadenMass: null,
					TypeApprovalNumber: null,
					NumberOfSeats: null,
					NumberOfStandingPlaces: null,
					EngineIDNumber: null,
					VehicleIDNumber: null,
					NumberOfAxles: null,
					Category: null,
					Color: null,
					RestrictionToChangeOwner: null,
					Load: null
				}
			],
			FullOwnerName: 'Borko Drazilovic',
			FullUserName: ' ',
			OwnerJMBGMB: null,
			UserJMBGMB: null
		},
		{
			ID: 51,
			OwnerPersonalNo: null,
			OwnerPIB: null,
			OwnerName: 'Gordana - Goca',
			OwnerSurnameOrBusinessName: 'Europen',
			OwnerAddress: null,
			OwnerPhone: null,
			OwnerEmail: null,
			UserPersonalNo: null,
			UserPIB: null,
			UserName: null,
			UserSurnameOrBusinessName: null,
			UserAddress: null,
			UserPhone: null,
			UserEmail: null,
			RecommendedBy: null,
			Vehicles: [
				{
					ID: 50,
					RegistrationNumber: 'BG',
					FirstRegistrationDate: null,
					ProductionYear: null,
					Make: 'Skoda',
					Model: 'Fabia',
					Type: null,
					EnginePowerKW: null,
					EngineCapacity: null,
					FuelType: null,
					PowerWeightRatio: null,
					Mass: null,
					MaxPermissibleLadenMass: null,
					TypeApprovalNumber: null,
					NumberOfSeats: null,
					NumberOfStandingPlaces: null,
					EngineIDNumber: null,
					VehicleIDNumber: null,
					NumberOfAxles: null,
					Category: null,
					Color: null,
					RestrictionToChangeOwner: null,
					Load: null
				}
			],
			FullOwnerName: 'Gordana - Goca Europen',
			FullUserName: ' ',
			OwnerJMBGMB: null,
			UserJMBGMB: null
		},
		{
			ID: 50,
			OwnerPersonalNo: null,
			OwnerPIB: null,
			OwnerName: 'Milos',
			OwnerSurnameOrBusinessName: 'Raicevic',
			OwnerAddress: 'Strahinica Bana 37',
			OwnerPhone: null,
			OwnerEmail: null,
			UserPersonalNo: null,
			UserPIB: null,
			UserName: null,
			UserSurnameOrBusinessName: null,
			UserAddress: null,
			UserPhone: null,
			UserEmail: null,
			RecommendedBy: null,
			Vehicles: [
				{
					ID: 49,
					RegistrationNumber: 'BG',
					FirstRegistrationDate: null,
					ProductionYear: null,
					Make: 'Audi',
					Model: 'A6',
					Type: null,
					EnginePowerKW: null,
					EngineCapacity: null,
					FuelType: null,
					PowerWeightRatio: null,
					Mass: null,
					MaxPermissibleLadenMass: null,
					TypeApprovalNumber: null,
					NumberOfSeats: null,
					NumberOfStandingPlaces: null,
					EngineIDNumber: null,
					VehicleIDNumber: null,
					NumberOfAxles: null,
					Category: null,
					Color: null,
					RestrictionToChangeOwner: null,
					Load: null
				}
			],
			FullOwnerName: 'Milos Raicevic',
			FullUserName: ' ',
			OwnerJMBGMB: null,
			UserJMBGMB: null
		}
	],
	Total: 3
};

export default FakeClients;
