//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOffice.DB.DBModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TOfficeEntities : DbContext
    {
        public TOfficeEntities()
            : base("name=TOfficeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientRegistrationDocumentData> ClientRegistrationDocumentData { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<RegistrationDocumentData> RegistrationDocumentData { get; set; }
        public virtual DbSet<RegistrationVehicleData> RegistrationVehicleData { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VehicleRegistrationInstallments> VehicleRegistrationInstallments { get; set; }
        public virtual DbSet<VehicleRegistrations> VehicleRegistrations { get; set; }
    
        public virtual int Report_CostsByPeriod(Nullable<System.DateTime> dateFrom, Nullable<System.DateTime> dateTo)
        {
            var dateFromParameter = dateFrom.HasValue ?
                new ObjectParameter("dateFrom", dateFrom) :
                new ObjectParameter("dateFrom", typeof(System.DateTime));
    
            var dateToParameter = dateTo.HasValue ?
                new ObjectParameter("dateTo", dateTo) :
                new ObjectParameter("dateTo", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Report_CostsByPeriod", dateFromParameter, dateToParameter);
        }
    }
}
