//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T_Office.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientRegistrationDocumentData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientRegistrationDocumentData()
        {
            this.VehicleRegistrations = new HashSet<VehicleRegistrations>();
        }
    
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int RegistrationDocumentDataID { get; set; }
        public bool IsExpired { get; set; }
    
        public virtual Clients Clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleRegistrations> VehicleRegistrations { get; set; }
        public virtual RegistrationDocumentData RegistrationDocumentData { get; set; }
    }
}
