//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T_Office.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationDocumentData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegistrationDocumentData()
        {
            this.ClientRegistrationDocumentData = new HashSet<ClientRegistrationDocumentData>();
            this.RegistrationVehicleData = new HashSet<RegistrationVehicleData>();
        }
    
        public int ID { get; set; }
        public string IssuingState { get; set; }
        public string CompetentAuthority { get; set; }
        public string IssuingAuthority { get; set; }
        public string UnambiguousNumber { get; set; }
        public Nullable<System.DateTime> IssuingDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public string SerialNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientRegistrationDocumentData> ClientRegistrationDocumentData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationVehicleData> RegistrationVehicleData { get; set; }
    }
}
