//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T_Office.DAL.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleRegistrationInstallments
    {
        public int ID { get; set; }
        public int VehicleRegistrationID { get; set; }
        public System.DateTime InstallmentDate { get; set; }
        public decimal Amount { get; set; }
        public bool IsAdminBan { get; set; }
        public string Note { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
    
        public virtual VehicleRegistrations VehicleRegistrations { get; set; }
    }
}
